### ISSUE TITLE
Render error

### ISSUE THREAD

**Issue by derevandal** [MicroDroid/vue-invisible-recaptcha#2]
I follow tha steps in README, but I got this error.

```js
[vue-router] Failed to resolve async component default: SyntaxError: Unexpected token <
[vue-router] uncaught error during route navigation:
D:\projects\idepead-unifran\node_modules\vue-invisible-recaptcha\src\InvisibleRecaptcha.vue:1
(function (exports, require, module, __filename, __dirname) { <template>
                                                              ^
SyntaxError: Unexpected token <
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:588:28)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at r (D:\projects\idepead-unifran\node_modules\vue-server-renderer\build.js:7758:16)
    at Object.<anonymous> (server-bundle.js:4177:18)
    at __webpack_require__ (server-bundle.js:27:30)
    at Object.97 (pages\euquero\index.d432ea5d1be16c5495a2.js:78:82)
    at __webpack_require__ (server-bundle.js:27:30)
    at Object.77 (pages\euquero\index.d432ea5d1be16c5495a2.js:9:263)
    at __webpack_require__ (server-bundle.js:27:30)
```

```js
//script
import InvisibleRecaptcha from 'vue-invisible-recaptcha'

export default {
  name: 'eu-quero-no-slug',
  components: {
    'invisible-recaptcha': InvisibleRecaptcha
  },
  data () {
    return {
      name: null,
      email: null,
      phone: null,
      select: 1,
      checkbox: true,
      formSubmitted: false
    }
  }
}
```

```pug
// template
invisible-recaptcha(sitekey="6Ld0vTQUAAAAAAbfmFV28bTImZarA-gQ5bBikGar" :validate="prepare" :callback="doSomething" class="btn btn-danger" type="submit" id="do-something-btn" :disabled="loading") Do something!
.button-container
    button.button(type="submit"): span Enviar
```

**Comment by MicroDroid** [comment]
Do you have `vue-loader` properly loaded and set up?

**Comment by derevandal** [comment]
@MicroDroid 
Yes, when i remove this code, the error disappears.

**Comment by MicroDroid** [comment]
Make sure your webpack config does not exclude `node_modules` or something, the problem has totally to do with your build config
